Feature/tvq2mws q view hr to talk
MichalTomczakSE/Mega-K-Headhunter-Front pull request #12
Opened 2023-05-05 18:35 UTC by AgnieszkaPawlak

Create hr view layout.
- Sections: pagination, search, filter, links.

2023-05-05 19:52 UTC, MichalTomczakSE requested changes

2023-05-05 19:52 UTC, MichalTomczakSE commented on components/hrInfo/Pagination/Pagination.tsx
> +        <ReactPaginate
I dont like this pagination, since it looks really diffrent than [here](https://xd.adobe.com/view/864faeb9-d762-4277-a5d1-5b7565dcf543-d31c/screen/faa8be4a-a848-43db-8a13-c7d3e2c1e604/?utm_campaign=WYNIKI+TWOJEGO+ZALICZENIA+MEGAK+-+GRATULACJE&utm_medium=email&utm_source=newsletter&utm_term=2023-04-18). 

If we want stick to that, ill preffer to change some styles of it, maybe add primary-red outline for active, and add some spacing - margins between and larger paddings.

2023-05-05 19:52 UTC, MichalTomczakSE commented on components/hrInfo/Search/searchStudent.tsx
> +        placeholder="szukaj"
Add extra padding for this input, spacing between magnifier and placeholder and make first placeholder letter Uppercase.

2023-05-05 19:52 UTC, MichalTomczakSE commented on components/hrInfo/linkHr/linkComponent.tsx
> +
Import next router there

2023-05-05 19:52 UTC, MichalTomczakSE commented on components/hrInfo/linkHr/linkComponent.tsx
> +          className="py-6 focus:border-b-[3px] focus:border-b-secondary-red "
Instead of pseudoclass focus, import router and refactor like this: 

```js
 <Link className={router.asPath =="/dashboard/hr/available-students" ? 'border-b-[3px] border-b-secondary-red' : ''  }
 ```
 Because focus works only onclick/after click and border will dissapear, when user clicks on other things.

2023-05-05 19:52 UTC, MichalTomczakSE commented on components/hrInfo/linkHr/linkComponent.tsx
> +          className=" py-6 focus:border-b-[3px] focus:border-b-secondary-red"
Same as above, but with different path 😄

2023-05-05 19:52 UTC, MichalTomczakSE commented on pages/dashboard/hr/availableStudents.tsx
> +      <div> Dostępni kursanci</div>
Since this component is going to be same as toTalk, you have choice to copy same structure here, or create Layout, or again add router, and depending on path fetch different data.

2023-05-05 19:52 UTC, MichalTomczakSE commented on pages/dashboard/hr/toTalk.tsx
> +        <Header />
This Header component needs to be outside of Container component due to styling. 
```js
<>
<Header />
<Container> 
...
</Container>
<>
```

2023-05-05 19:52 UTC, MichalTomczakSE commented on yarn.lock
You can delete yarn lock in next commit, due to merge conflict. commit Package json instead.

2023-05-08 19:48 UTC, MichalTomczakSE approved these changes

2023-05-08 20:11 UTC, ZrodoZrodo approved these changes

2023-05-09 15:12 UTC, merged