Feature/3vv sx bs j navbar component
MichalTomczakSE/Mega-K-Headhunter-Front pull request #5
Opened 2023-04-23 10:18 UTC by GosiekPiernik

2023-04-23 10:47 UTC, MichalTomczakSE requested changes
Overall everything looks good. I think you can add just some small changes I have mentioned in comments :).

2023-04-23 10:47 UTC, MichalTomczakSE commented on components/common/Header.tsx
> +                                <Link href={link.href} key={link.href} className="py-2.5">{link.label}</Link>
There may be problems. The key is a unique value, and the `href` value in `links` object for both elements is the same. Please change one value to '/' if you are unsure what the redirect paths will look like.

2023-04-23 10:47 UTC, MichalTomczakSE commented on pages/index.tsx
Since we are currently not using 'Image' and 'Inter' font in the project, you can delete these lines and leave Header import only.

2023-04-23 10:47 UTC, MichalTomczakSE commented on components/common/Header.tsx
> +export default function Header() {
Would you like to change `export default` to `export const Header = () => {` ?

2023-04-23 13:28 UTC, ZrodoZrodo approved these changes
i don't have any comments

2023-04-24 21:35 UTC, MichalTomczakSE approved these changes

2023-04-24 21:39 UTC, merged