Feature/hgrmh8lr create login form
MichalTomczakSE/Mega-K-Headhunter-Front pull request #6
Opened 2023-04-23 16:30 UTC by ZrodoZrodo

2023-04-23 18:29 UTC, MichalTomczakSE requested changes

2023-04-23 18:29 UTC, MichalTomczakSE commented on components/Button.tsx
> +export const Button = ({ children }) => {
Create some types for children ex. interface ButtonProps { children: ... }

2023-04-23 18:29 UTC, MichalTomczakSE commented on components/Button.tsx
> +      type={"submit"}
Just for cosmetic purposes - you can delete curly braces if you are passing just string.

2023-04-23 18:29 UTC, MichalTomczakSE commented on components/registerAndForgottenPassword.tsx
> +  console.log("ffdsfd");
🗡️ 🗡️ 🗡️

2023-04-23 18:29 UTC, MichalTomczakSE commented on components/registerAndForgottenPassword.tsx
> +    //ToDo api connection
Not necessary comment in code

2023-04-23 18:29 UTC, MichalTomczakSE commented on components/registerAndForgottenPassword.tsx
> +    console.log(router.pathname);
Remove console logs from code.

2023-04-23 18:29 UTC, MichalTomczakSE commented on components/registerAndForgottenPassword.tsx
> +              <img
Replace img tag with next/Image component: 

https://nextjs.org/docs/api-reference/next/image

2023-04-23 18:29 UTC, MichalTomczakSE commented on components/registerAndForgottenPassword.tsx
> +                  "https://static1.s123-cdn-static-a.com/uploads/5191798/400_609bb5e2d9a39.png"
Download and save image in public/images/logo.png

2023-04-23 18:29 UTC, MichalTomczakSE commented on components/registerAndForgottenPassword.tsx
> +  console.log("ffdsfd");
Return some mock data instead of console.log, maybe try to get data from inputs

2023-04-23 18:29 UTC, MichalTomczakSE commented on pages/login.tsx
Same issues like in registerAndForgottenPassword.tsx - delete console.logs, replace img with Image

2023-04-23 18:29 UTC, MichalTomczakSE commented on pages/forgottenPassword.tsx
> +const ForgottenPassword = () => {
Change to ForgottenPasswordPage

2023-04-25 13:00 UTC, MichalTomczakSE approved these changes

2023-04-26 06:53 UTC, AgnieszkaPawlak commented on components/registerAndForgottenPassword.tsx
> +
Imports should be in the proper order, first external and then internal.

2023-04-26 06:56 UTC, AgnieszkaPawlak commented on pages/register.tsx
> +const register = () => {
Function name shold start with a capital letter.

2023-04-26 07:34 UTC, AgnieszkaPawlak commented on components/common/Input.tsx
This component cannot be used throughout the application. Either it will be used only in your part, or it needs to be completely redesigned.

2023-04-26 07:39 UTC, AgnieszkaPawlak commented on components/common/Button.tsx
> +  type?:"submit" | "reset",
You should also add the type "button".

2023-04-26 07:43 UTC, AgnieszkaPawlak commented on components/common/Button.tsx
> +export const Button = ({ children,type,color }: ButtonProps ) => {
You can assign default values such as :  type="button" color="bg-primary-red"

2023-04-26 07:46 UTC, AgnieszkaPawlak commented on components/common/Button.tsx
> +  color?:string|undefined,
I have a problem with this undefind color  type. In my opinion, button should have a defined color.

2023-04-26 07:50 UTC, AgnieszkaPawlak commented on components/common/Button.tsx
> +      type={type?type:"button"}
If you assign the "type" in the props, you can change this line to type={type}

2023-04-26 13:58 UTC, ZrodoZrodo commented on components/common/Button.tsx
> +      type={type?type:"button"}
We dont must write type in component so i must check this here

2023-04-26 15:37 UTC, AgnieszkaPawlak approved these changes

2023-04-26 15:50 UTC, merged